### ISSUE TITLE
e站捐赠方案

### ISSUE THREAD

**Issue by HoriYuko** [kk9448/ehDonate#2]
请问除了通过虚拟货币交易所为e站进行捐赠的方案，是否还有其他更加便捷的方式可以捐赠吗? [不需要进行身份验证*(重要)]

ps:本人对于e站的需求非常的有限 (赞助成为铜星)

 *[因为网络原因无法使用电报；(使用email)]

**Comment by kk9448** [comment]
e站目前只接受虚拟货币进行捐赠, 不接受其他方式, 身份验证也是保护个人资产的一个重要环节, 不用过分在意
